### ISSUE TITLE
Request: Release a VST Instrument Version for ease of use with midi input

### ISSUE THREAD

**Issue by starwarswii** [ddf/evaluator#2]
First off let me say that I really love this plugin. All the additional input variables and helper operations (e.g `Fn`) really elevate this from just a bytebeat interpreter in a VST package to it's own great thing.

It's great to use, but one thing I struggled with was getting my DAW to send midi data to it as it presents itself as an effect plugin.
[I understand why it was made as an effect plugin](https://itch.io/t/277364/vst-as-a-synth), but as someone who was trying to use it as a cool glitch instrument played by midi, it was a roadblock.
I eventually got it to work by running it within [Metaplugin](https://ddmf.eu/metaplugin-chainer-vst-au-rtas-aax-wrapper/) (which is a fantastic plugin to use if your DAW doesn't support advanced routing, by the way), but I think making a release that works as an instrument would reduce the hassle quite a bit.

If doing so requires dropping support for receiving audio via `[0]` and `[1]` in that version, that's fine. I'm more interested in creating bytebeat sounds controlled by the notes played.
Although _"you don't need MIDI to run Evaluator"_ (from the link above), I'd say it's definitely the best and most defining feature of Evaluator.

Thank you for producing this plugin, and hopefully it's an easy change to rebuild it to present itself to the daw as an instrument plugin.

**Comment by ddf** [comment]
I've made a note in my TODO about this. After some thought, I think it's a totally reasonable request and makes more sense than having it be an effect.

**Comment by starwarswii** [comment]
@ddf wow, I didn't actually expect to get a response. Thanks!
